
(
    KIND_NONE,
    KIND_ARCHER,
    KIND_HEIR,
    KIND_LORD,
    KIND_SHAPESHIFTER,
    KIND_SOLDIER,
    KIND_SPY,
    KIND_AMBUSH,
    KIND_ASSASSINATION,
    KIND_CONSPIRACY,
    KIND_ROYAL_DECREE,
    KIND_MAX,
) = range(12)

(
    PHASE_NONE,
    PHASE_PLACE,
    PHASE_REVEAL,
    PHASE_ACT,
    PHASE_MAX,
) = range(5)

(
    EFFECT_NONE,
    EFFECT_PLACE,
    EFFECT_REVEAL,
    EFFECT_INCREASE,
    EFFECT_EARN,
    EFFECT_STEAL,
    EFFECT_KILL,
    EFFECT_SWAP,
    EFFECT_MIMIC,
    EFFECT_MAX,
) = range(10)
